export const SIMILARITY_FLOOR = 0.5;
export const PREFACE_INCLUSION_THRESHOLD = 0.7;
export const PREFACE_FILE_CONFIDENCE_THRESHOLD = 0.6;
export const MIN_SIMILAR_TASKS_FOR_SUGGESTION = 3;
export const MIN_CORPUS_SIZE = 10;
export const ABANDONED_TASK_DAYS = 7;

export const SUGGESTION_THRESHOLDS = {
  SIMILARITY_FLOOR,
  PREFACE_INCLUSION_THRESHOLD,
  PREFACE_FILE_CONFIDENCE_THRESHOLD,
  MIN_SIMILAR_TASKS_FOR_SUGGESTION,
  MIN_CORPUS_SIZE,
  ABANDONED_TASK_DAYS,
} as const;
