export const quotaSafeOperatingContract = [
  '## Quota-safe Colony operating contract',
  'Coordination truth lives in Colony. Use OMX for runtime memory summaries. Use available MCP servers for repo, GitHub, CI, and docs context before guessing.',
  '',
  'Before work:',
  '1. Call hivemind_context.',
  '2. Call attention_inbox.',
  '3. Call task_ready_for_agent.',
  '4. Accept a pending handoff with task_accept_handoff when one is present, or explicitly decline it.',
  '5. Claim the subtask with task_plan_claim_subtask when ready work returns claim args.',
  '6. Claim each touched file with task_claim_file before edits.',
  '7. Write task_note_working with branch, task, blocker, next, and evidence.',
  '',
  'During work:',
  '1. Update task_note_working after meaningful progress.',
  '2. Keep the next step explicit.',
  '3. Run focused verification for the touched behavior.',
  '',
  'Before quota/session stop:',
  '1. Emit a quota_exhausted handoff with task_hand_off or task_relay.',
  '2. Include claimed files, dirty files, branch, last verification, and next step.',
  '3. Do not leave strong claims without a handoff or TTL.',
].join('\n');
