export const quotaSafeOperatingContract = [
  '## Quota-safe Colony operating contract',
  'Coordination truth lives in Colony. Use OMX for runtime memory summaries. Use available MCP servers for repo, GitHub, CI, and docs context before guessing.',
  '',
  'RTK command policy:',
  '1. Always prefix shell commands with `rtk` for token-optimized output and savings tracking.',
  '2. Use RTK shorthands for file, git, GitHub, test, build, lint, package, container, cloud, data, and log commands, for example `rtk ls`, `rtk read`, `rtk grep`, `rtk git status`, `rtk gh pr view`, `rtk pytest`, `rtk tsc`, and `rtk lint`.',
  '3. Use `rtk err <cmd>` or `rtk test <cmd>` when a command is noisy and failures are the only needed output.',
  '4. Use `rtk proxy <command>` when exact raw command behavior is required while still routing through RTK.',
  '5. If `rtk` is unavailable, record that fact, run the underlying command only as needed, and keep output compact.',
  '',
  'Before work:',
  '1. Call hivemind_context.',
  '2. Call attention_inbox.',
  '3. Call task_ready_for_agent.',
  '4. Accept a pending handoff with task_accept_handoff when one is present, or explicitly decline it.',
  '5. Claim the subtask with task_plan_claim_subtask when ready work returns claim args.',
  '6. Claim each touched file with task_claim_file before edits.',
  '7. Write task_note_working with branch, task, blocker, next, and evidence.',
  '',
  'During work:',
  '1. Update task_note_working after meaningful progress.',
  '2. Keep the next step explicit.',
  '3. Run focused verification for the touched behavior.',
  '',
  'Shutdown / finish contract:',
  '1. Before stopping, run git status and identify dirty files.',
  '2. If dirty files exist, commit finished work, hand off unfinished work, or clean intentionally abandoned edits.',
  '3. Write task_note_working with branch, task, dirty files, blocker, next step, and evidence.',
  '4. Release or weaken claims before abandoning work so stale strong ownership does not block the next agent.',
  '',
  'Before quota/session stop:',
  '1. Emit a quota_exhausted handoff with task_hand_off or task_relay, or release owned claims.',
  '2. Include claimed files, dirty files from git status, branch, last verification, and next step.',
  '3. Mark claims handoff-pending or release them before exit; do not leave strong claims without a handoff or TTL.',
  '4. When unsure, run coordination sweep guidance first and follow its release/handoff recommendation.',
].join('\n');
